"""Add saas models

Revision ID: 64fd0b352871
Revises: 35d0eacda6f9
Create Date: 2026-07-13 11:34:30.984501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fd0b352871'
down_revision: Union[str, Sequence[str], None] = '35d0eacda6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('filters_used', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_history_id'), 'export_history', ['id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_id'), 'saved_searches', ['id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_params', sa.JSON(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('lead_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_result_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_timelines_id'), 'lead_timelines', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_date', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.add_column('search_results', sa.Column('has_facebook', sa.Boolean(), nullable=True))
    op.add_column('search_results', sa.Column('has_instagram', sa.Boolean(), nullable=True))
    op.add_column('search_results', sa.Column('has_linkedin', sa.Boolean(), nullable=True))
    op.add_column('search_results', sa.Column('has_twitter', sa.Boolean(), nullable=True))
    op.add_column('search_results', sa.Column('has_youtube', sa.Boolean(), nullable=True))
    op.add_column('search_results', sa.Column('has_whatsapp', sa.Boolean(), nullable=True))
    op.add_column('search_results', sa.Column('lead_status', sa.String(), nullable=True))
    op.add_column('search_results', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('search_results', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('search_results', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('search_results', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_results', 'created_at')
    op.drop_column('search_results', 'longitude')
    op.drop_column('search_results', 'latitude')
    op.drop_column('search_results', 'ai_summary')
    op.drop_column('search_results', 'lead_status')
    op.drop_column('search_results', 'has_whatsapp')
    op.drop_column('search_results', 'has_youtube')
    op.drop_column('search_results', 'has_twitter')
    op.drop_column('search_results', 'has_linkedin')
    op.drop_column('search_results', 'has_instagram')
    op.drop_column('search_results', 'has_facebook')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_lead_timelines_id'), table_name='lead_timelines')
    op.drop_table('lead_timelines')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_saved_searches_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_export_history_id'), table_name='export_history')
    op.drop_table('export_history')
    # ### end Alembic commands ###
